### ISSUE TITLE
Vorschlag - Neuer Blog Feed - kleinfreund.de (von Philipp Rudloff @ Weimar)

### ISSUE THREAD

**Issue by geraldb** [Quintus/rubyplanet#1]
Servus, bei Interesse ein Blog in Deutsch von Phillpp Rudloff (etwa mit Beitraegen ueber Jekyll etc.) @ kleinfreund.de  Cheers.

**Comment by Quintus** [comment]
Die eigentlich interessante Frage ist, warum GitHub mir keine Notifications sendet, wenn hier jemand einen Issue aufmacht. Ich kann doch nicht ständig alle Repositories händisch abklappern.

kleinfreund ist drin, jetzt dank #2 auch mit aktueller URL. Danke aber auf jeden Fall nochmal für den Hinweis.

Vale,
Quintus
